dbench.h: use bits/types.h instead of defining uint32
This fixes this compilation warning:

Compiling nfsio.o
gcc -g -g -O2 -Wall -W -I. -DVERSION=\"4.00\"
-DDATADIR=\"/usr/local/share\" `pkg-config --cflags libtirpc`
-Wimplicit-fallthrough=2 -c nfsio.c -o nfsio.o
In file included from nfsio.c:20:
dbench.h:105:16: error: two or more data types in declaration specifiers
  105 | #define uint32 unsigned int
      |                ^~~~~~~~
nfs.h:54:16: note: in expansion of macro ‘uint32’
   54 | typedef u_long uint32;
      |                ^~~~~~
dbench.h:105:25: error: two or more data types in declaration specifiers
  105 | #define uint32 unsigned int
      |                         ^~~
nfs.h:54:16: note: in expansion of macro ‘uint32’
   54 | typedef u_long uint32;
      |                ^~~~~~
In file included from nfsio.c:21:
nfs.h:54:1: warning: useless type name in empty declaration
   54 | typedef u_long uint32;
      | ^~~~~~~

Signed-off-by: Luis Chamberlain <mcgrof@kernel.org>